
import pandas as pd
import os
import sys
import pyranges as pr

p = os.path.dirname(os.path.dirname(os.getcwd()))+'/scripts/'
sys.path.append(p)

from sm_utils import *
from utils import *
# from vcf_utils import *

c_dir = '../common/'

meta_file = '../config.tsv'
configfile: '../config.yml'

include: f'{c_dir}download.smk'
include: f'{c_dir}samtools.smk'
include: f'{c_dir}winnowmap.smk'
include: f'{c_dir}bigwig.smk'
include: f'{c_dir}variant_calling.smk'
include: f'{c_dir}formatting.smk'
include: f'{c_dir}phasing.smk'
include: f'{c_dir}cerberus.smk'
include: f'{c_dir}bedtools.smk'
include: f'{c_dir}transdecoder.smk'
include: f'{c_dir}protein.smk'
include: f'{c_dir}minimap2.smk'
include: f'{c_dir}stats.smk'
include: f'{c_dir}lr-kallisto.smk'
include: f'{c_dir}kallisto.smk'
include: f'{c_dir}suppa.smk'

# sample information
meta_file = '../config.tsv'

meta_df = load_meta()
meta_df['lab_sample'] = meta_df['lab_number_sample'].astype(str)+'_'+\
                      meta_df['lab_sampleid'].astype(str)+'_'+\
                      meta_df['cell_line_id'].astype(str)

rule lapa_config:
    input:
        files = # Q10 bams
    resources:
        threads = 1,
        mem_gb = 1
    output:
        config = config['lr']['lapa']['config']
    run:
        df = get_lapa_run_info(wildcards, params.df,
                    config['lr']['talon']['bam_sort'],
                    dataframe=True)
        # df = df[['sample', 'dataset', 'lapa_file']].copy(deep=True)
        # df.columns = ['sample', 'dataset', 'path']

        df = df[['dataset', 'sample', 'lapa_file']].copy(deep=True)

        # argggggh rename these files in the opposite manner because
        # hasan and I have opposite definitions of "sample" and "dataset"
        df.columns = ['sample', 'dataset', 'path']

        df.to_csv(output.config, sep=',', index=False)

rule lapa_tss:
    input:
        samples = ,
        fa = ,
        annot = ,
        chrom_sizes =
    resources:
    output:
        directory()
    conda:
        "lapa"
    shell:
        """
        lapa_tss --alignment {input.config} \
        	--fasta {input.fa} \
        	--annotation {input.annot} \
        	--chrom_sizes {input.chrom_sizes} \
        	--output_dir {output}
        """
