import pandas as pd
import os
import sys

p = os.path.dirname(os.path.dirname(os.getcwd()))+'/scripts/'
sys.path.append(p)
#
# from sm_utils import *
# from utils import *
# from vcf_utils import *

c_dir = '../common/'

meta_file = 'config.tsv'
configfile: '../config.yml'

include: f'{c_dir}download.smk'
include: f'{c_dir}samtools.smk'
include: f'{c_dir}winnowmap.smk'
include: f'{c_dir}bigwig.smk'
include: f'{c_dir}variant_calling.smk'
include: f'{c_dir}formatting.smk'
include: f'{c_dir}phasing.smk'
include: f'{c_dir}cerberus.smk'

rule all:
    input:
        expand(config['lr']['suppa']['psi'],
               event=['A3', 'A5', 'AF', 'AL', 'MX', 'RI', 'SE'])

# the input format is so dumb
# rule fmt_ab:
#     input:
#         ab = config['lr']['kallisto']['merge_matrix_tpm_tsv']
#     resources:
#         threads = 1,
#         nodes = 1
#     output:
#         ab = config['lr']['suppa']['fmt_ab']
#     run:
#         df = pd.read_csv(input.ab, sep='\t')
#         df = df.set_index('transcript_id')
#         df.index.name = ''
#         df.to_csv(output.ab, sep='\t')

rule suppa_generate_events:
    input:
        gtf = config['lr']['gtf_filt_with_genes']
    resources:
        mem_gb = 16,
        threads = 1
    params:
        opref = config['lr']['suppa']['events']['A3'].rsplit('_', maxsplit=2)[0]
    output:
        config['lr']['suppa']['events']['A3'],
        config['lr']['suppa']['events']['A5'],
        config['lr']['suppa']['events']['AF'],
        config['lr']['suppa']['events']['AL'],
        config['lr']['suppa']['events']['MX'],
        config['lr']['suppa']['events']['RI'],
        config['lr']['suppa']['events']['SE'],
    conda:
        'base'
    shell:
        """
        conda activate /gpfs/projects/bsc83/utils/conda_envs/suppa2
        /gpfs/projects/bsc83/utils/SUPPA-2.4/suppa.py generateEvents \
            -i {input.gtf} \
            -o {params.opref} \
            -f ioe \
            -e SE SS MX RI FL
        """

rule suppa_psi:
    resources:
        mem_gb = 16,
        threads = 1
    conda:
        'base'
    shell:
        """
        conda activate /gpfs/projects/bsc83/utils/conda_envs/suppa2
        /gpfs/projects/bsc83/utils/SUPPA-2.4/suppa.py psiPerEvent \
            --ioe-file {input.ioe} \
            --expression-file {input.filt_ab} \
            --o {params.opref}
        """

use rule suppa_psi as suppa_get_psi with:
    input:
        ioe = lambda wc:config['lr']['suppa']['events'][wc.event],
        filt_ab = config['lr']['suppa']['fmt_ab']
    params:
        opref = config['lr']['suppa']['psi'].rsplit('.psi', maxsplit=1)[0]
    output:
        config['lr']['suppa']['psi']
