import pandas as pd
import os
import sys

p = os.path.dirname(os.path.dirname(os.getcwd()))+'/scripts/'
sys.path.append(p)
#
# from sm_utils import *
# from utils import *
# from vcf_utils import *

c_dir = '../common/'

meta_file = 'config.tsv'
configfile: '../config.yml'

include: f'{c_dir}download.smk'
include: f'{c_dir}samtools.smk'
include: f'{c_dir}winnowmap.smk'
include: f'{c_dir}bigwig.smk'
include: f'{c_dir}variant_calling.smk'
include: f'{c_dir}formatting.smk'
include: f'{c_dir}phasing.smk'
include: f'{c_dir}cerberus.smk'

rule all:
    input:
        config['lr']['cerb']['ics']

# use rule wget as dl_enc with:
#     params:
#         link = config['lr']['gtf_link']
#     output:
#         out = temporary(config['lr']['gtf'])


use rule gtf_to_ic as enc_gtf_to_ic with:
    input:
        gtf = config['lr']['gtf_filt_with_genes']
    output:
        tsv = config['lr']['cerb']['ics']
