import pandas as pd
import os
import sys

p = os.path.dirname(os.path.dirname(os.getcwd()))+'/scripts/'
sys.path.append(p)

from sm_utils import *
from utils import *
# from vcf_utils import *

c_dir = '../common/'

meta_file = '../config.tsv'
configfile: '../config.yml'

include: f'{c_dir}download.smk'
include: f'{c_dir}samtools.smk'
include: f'{c_dir}winnowmap.smk'
include: f'{c_dir}bigwig.smk'
include: f'{c_dir}variant_calling.smk'
include: f'{c_dir}formatting.smk'
include: f'{c_dir}phasing.smk'
include: f'{c_dir}cerberus.smk'
include: f'{c_dir}bedtools.smk'
include: f'{c_dir}transdecoder.smk'
include: f'{c_dir}protein.smk'
include: f'{c_dir}minimap2.smk'
include: f'{c_dir}stats.smk'
include: f'{c_dir}lr-kallisto.smk'

rule all:
    input:
        config['lr']['gtf_gc_poder']

rule merge_gc_poder:
    input:
        ref_gtf = config['ref']['gtf'],
        new_gtf = config['lr']['gtf_filt_with_genes']
    resources:
        threads = 1,
        nodes = 2
    params:
        scripts_dir = p
    conda:
        'cerberus'
    output:
        gtf = config['lr']['gtf_gc_poder']
    shell:
        """
        python {params.scripts_dir}gc_poder_merge.py \
            {input.ref_gtf} \
            {input.new_gtf} \
            {output.gtf}
        """
#
