gtex:
    gtf_link: https://storage.googleapis.com/gtex_analysis_v9/long_read_data/flair_filter_transcripts.gtf.gz
    gtf_gz: ../../data/gtex/flair_filter_transcripts.gtf.gz
    gtf: ../../data/gtex/flair_filter_transcripts.gtf
    # filt_gtf: data/gtex/flair_filter_transcripts_no_novel_genes.gtf
    ab_link: https://storage.cloud.google.com/adult-gtex/long-read-data/v9/long-read-RNA-seq/quantification_flair_filter.tpm.txt.gz
    ab_gz: ../../data/gtex/gtex_abundance.tsv.gz
    ab: ../../data/gtex/gtex_abundance.tsv
    ab_fmt: ../../data/gtex/gtex_abundance_formatted.tsv

    cerberus:
      ics: ../../data/gtex/cerberus/ics.tsv
