ref:
    alt:
      fa_gz: ../../ref/{assembly}/{assembly}.fa.gz
      fa_mmi: ../../ref/{assembly}/{assembly}.fa.mmi
      t2t:
        link: https://hgdownload.soe.ucsc.edu/goldenPath/hs1/bigZips/hs1.fa.gz
      afr:
        link: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/610/035/GCA_003610035.2_CAAPA_Pan-Genome/GCA_003610035.2_CAAPA_Pan-Genome_genomic.fna.gz

    # fa: /gpfs/projects/bsc83/Data/assemblies/GRCh38/GRCh38.primary_assembly.genome.fa
    fa: ../../ref/hg38.fa
    fa_mmi: ../../ref/hg38.fa.mmi
    gtf: /gpfs/projects/bsc83/Data/gene_annotations/gencode/v47/gencode.v47.primary_assembly.annotation.gtf

    pc_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/gencode.v46.pc_translations.fa.gz
    pc_gz: ../../ref/pc_translations.fa.gz
    pc: ../../ref/pc_translations.fa
    pc_renamed: ../../ref/pc_translations_renamed.fa

    cpat:
      model_link: https://sourceforge.net/projects/rna-cpat/files/prebuilt_models/Human_logitModel.RData/download
      model: ../../ref/cpat/cpat_model.RData
      hexamer_link: https://sourceforge.net/projects/rna-cpat/files/prebuilt_models/Human_Hexamer.tsv/download
      hexamer: ../../ref/hexamer.tsv

gtex:
    gtf_link: https://storage.googleapis.com/adult-gtex/long-read-data/v9/long-read-RNA-seq/flair_filter_transcripts.gtf.gz
    gtf_gz: ../../data/gtex/flair_filter_transcripts.gtf.gz
    gtf: ../../data/gtex/flair_filter_transcripts.gtf
    # filt_gtf: data/gtex/flair_filter_transcripts_no_novel_genes.gtf
    ab_link: https://storage.googleapis.com/adult-gtex/long-read-data/v9/long-read-RNA-seq/quantification_flair_filter.tpm.txt.gz
    ab_gz: ../../data/gtex/gtex_abundance.tsv.gz
    ab: ../../data/gtex/gtex_abundance.tsv
    ab_fmt: ../../data/gtex/gtex_abundance_formatted.tsv

    cerb:
      ics: ../../data/gtex/cerb/ics.tsv

chess:
    gtf_link: https://github.com/chess-genome/chess/releases/download/v.3.1.3/chess3.1.3.GRCh38.gtf.gz
    gtf_gz: ../../data/chess/chess.gtf.gz
    gtf: ../../data/chess/chess.gtf

    cerb:
      ics: ../../data/chess/cerb/ics.tsv

enc:
  gtf_link: https://zenodo.org/records/10869841/files/cerberus.gtf?download=1
  gtf_gz: ../../data/enc/enc.gtf.gz
  gtf: ../../data/enc/enc.gtf

  cerb:
    ics: ../../data/enc/cerb/ics.tsv


lr:
  fastq: /gpfs/projects/bsc83/Projects/pantranscriptome/pclavell/02_ONT_preprocessing/data/q7/{lab_sample}_preprocessed_Q7.fastq.gz
  fastq_n_reads: ../../data/{sample}_fastq_n_reads.txt
  fastq_n_reads_summary: ../../data/fastq_n_reads.txt

  gtf: /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/merged/240909_merged_withoutchrEBV.gtf # whole post-merge GTF
  # gtf: /gpfs/home/bsc/bsc083001/mele_lab/projects/240706_pantranscriptome_cerberus_gtf_merge/merge_only_ics/data/flair/raw/GM10492_1.gtf # test for just one sample
  gtf_no_spike: ../../data/transcripts_no_spike.gtf
  gtf_no_spike_no_ebv: ../../data/transcripts_no_spike_no_ebv.gtf
  t_fa: ../../data/transcripts.fa

  transdecoder:
    pep: ../../data/transdecoder/transcripts.fa.transdecoder.pep
    gff3: ../../data/transdecoder/transcripts.fa.transdecoder.gff3
    cds: ../../data/transdecoder/transcripts.fa.transdecoder.cds
    bed: ../../data/transdecoder/transcripts.fa.transdecoder.bed

  orfanage:
    query: ../../data/protein/transcripts_orfanage_ready_query.gtf
    ready_annot: ../../data/protein/transcripts_orfanage_ready_annotation.gtf
    cds: ../../data/protein/transcripts_orfanage_cds.gtf
    cds_to_be_predicted: ../../data/protein/transcripts_cpat_cds_to_be_predicted.gtf
    cds_filtered: ../../data/protein/transcripts_orfanage_cds_filtered.gtf
    orfs: ../../data/protein/transcripts_orfanage_orfs.fa
    stop_codon_orf: ../../data/protein/transcripts_orfanage_cds_filtered_stop_codon_corrected.gtf
    missing_cds: ../../data/protein/transcripts_missing_cds.fa

  cpat:
    r: ../../data/protein/transcripts.r
    orf_seqs: ../../data/protein/transcripts.ORF_seqs.fa
    prob_tsv: ../../data/protein/transcripts.ORF_prob.tsv
    prob_best: ../../data/protein/transcripts.ORF_prob.best.tsv
    log: ../../data/protein/transcripts_cpat.output
    err: ../../data/protein/transcripts_cpat.error
    no_orf: ../../data/protein/transcripts.no_ORF.txt
    orf_remaining: ../../data/protein/transcripts.ORF_remaining.tsv
    orf_completeness: ../../data/protein/transcripts_ORF_completeness.tsv
    cds_coords: ../../data/protein/transcripts_cpat_with_cds.gtf
    unsourced: ../../data/protein/transcripts_protein_unsourced.gtf
    protein: ../../data/protein/transcripts_protein.gtf
    orf: ../../data/protein/transcripts_ORF.fa
    protein_fa: ../../data/protein/transcripts_protein.fa

  blast:
    out: ../../data/protein/transcripts_blastp.out
    blast_db: ../../data/protein/gencode.pc_translations_renamed.pog

  sqanti_protein:
      ref_exons: ../../data/protein/transcripts_gencode.transcript_exons_only.gtf
      ref_cds_renamed: ../../data/protein/transcripts_gencode.cds_renamed_exon.gtf
      data_exons: ../../data/protein/transcripts.transcript_exons_only.gtf
      data_cds_renamed: ../../data/protein/transcripts.cds_renamed_exon.gtf
      best_orf: ../../data/protein/transcripts_best_orf.tsv
      classified: ../../data/protein/transcripts.sqanti_protein_classification.tsv

  protein:
    summary: ../../data/protein/transcripts_protein_annotation.tsv

  map:
    sam: ../../data/map/{assembly}/{sample}.sam
    sam_filt: ../../data/map/{assembly}/{sample}_filt.sam
    bam: ../../data/map/{assembly}/{sample}.bam
    bam_sort: ../../data/map/{assembly}/{sample}_sorted.bam
    bam_ind: ../../data/map/{assembly}/{sample}_sorted.bam.bai
    bam_n_reads: ../../data/map/{assembly}/{sample}_n_reads.txt
    bam_n_reads_summary: ../../data/map/{assembly}/n_reads_summary.tsv
    bam_mapqs: ../../data/map/{assembly}/{sample}_mapqs.txt
    bam_mapqs_summary: ../../data/map/{assembly}/mapqs_summary.txt
    bam_query_covs: ../../data/map/{assembly}/{sample}_query_cov.tsv
    bam_query_covs_summary: ../../data/map/{assembly}/query_cov_summary.tsv




  #
  #   cds: ../../data/orfanage/transcripts.cds.gtf
  #   cds_pred: ../../data/orfanage/transcripts.cds_pred.gtf
  #   cds_filt: ../../data/orfanage/transcripts.cds_filt.gtf
  #   cds_stop: ../../data/orfanage/transcripts.orfs_stop.fa
  #   cds_stop_corr: ../../data/orfanage/transcripts.orfs_stop_corr.gtf
  #   cds_for_cpat: ../../data/orfanage/transcripts.cds_for_cpat.fa
  #
  # cpat:
  #   r: ../../data/cpat/transcripts.r
  #   orf_fa: ../../data/cpat/transcripts_ORF_seqs.fa
  #   prob: ../../data/cpat/transcripts_ORF_prob.tsv
  #   prob_best: ../../data/cpat/transcripts_ORF_prob.best.tsv
  #   log: ../../data/cpat/transcripts_cpat.output
  #   err: ../../data/cpat/transcripts_cpat.error
  #   no_orf: ../../data/cpat/transcripts_no_ORF.txt
  #   filt: ../../data/cpat/transcripts_ORF_remaining.tsv
  #   orf_complete: ../../data/cpat/transcripts_ORF_completeness.tsv
  #   cds_coords: ../../data/cpat/transcripts_cpat_with_cds.gtf
  #   protein_unsourced: ../../data/cpat/transcripts_protein_unsourced.gtf


  novel_gene:
    tids: /gpfs/projects/bsc83/Projects/pantranscriptome/pclavell/04_transcriptome_assembly/04_evaluation/02_sqanti/data/240909merge/novelgene_transcripts.txt
    gtf: ../../data/novel_gene/novel_genes.gtf
    gtf_built: ../../data/novel_gene/novel_genes_built.gtf
    gtf_fmt: ../../data/novel_gene/novel_genes_fmt.gtf
    gtf_nov_known_gene: ../../data/transcripts_novel_gene_loci.gtf




params:
  orfanage:
    min_orf_len_nt: 100
  cpat:
    top_orf: 50
    cutoff_1: 0.725
    cutoff_2: 0.364
  blast:
    eval: 1.0e-10

software:
  buildLoci: /gpfs/home/bsc/bsc083001/mele_lab/bin/buildLoci/buildLoci.pl
