ref:
    fa: /gpfs/projects/bsc83/Data/assemblies/GRCh38/GRCh38.primary_assembly.genome.fa
    gtf: /gpfs/projects/bsc83/Data/gene_annotations/gencode/v47/gencode.v47.primary_assembly.annotation.gtf

gtex:
    gtf_link: https://storage.googleapis.com/adult-gtex/long-read-data/v9/long-read-RNA-seq/flair_filter_transcripts.gtf.gz
    gtf_gz: ../../data/gtex/flair_filter_transcripts.gtf.gz
    gtf: ../../data/gtex/flair_filter_transcripts.gtf
    # filt_gtf: data/gtex/flair_filter_transcripts_no_novel_genes.gtf
    ab_link: https://storage.googleapis.com/adult-gtex/long-read-data/v9/long-read-RNA-seq/quantification_flair_filter.tpm.txt.gz
    ab_gz: ../../data/gtex/gtex_abundance.tsv.gz
    ab: ../../data/gtex/gtex_abundance.tsv
    ab_fmt: ../../data/gtex/gtex_abundance_formatted.tsv

    cerb:
      ics: ../../data/gtex/cerb/ics.tsv

chess:
    gtf_link: https://github.com/chess-genome/chess/releases/download/v.3.1.3/chess3.1.3.GRCh38.gtf.gz
    gtf_gz: ../../data/chess/chess.gtf.gz
    gtf: ../../data/chess/chess.gtf

    cerb:
      ics: ../../data/chess/cerb/ics.tsv

lr:
  gtf: /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/merged/240906_merged_gtf_missing_2_lyric.gtf # change this eventually
  gtf_no_spike: ../../data/transcripts_no_spike.gtf
  t_fa: ../../data/transcripts.fa

  transdecoder:
    pep: ../../data/transdecoder/transcripts.fa.transdecoder.pep
    gff3: ../../data/transdecoder/transcripts.fa.transdecoder.gff3
    cds: ../../data/transdecoder/transcripts.fa.transdecoder.cds
    bed: ../../data/transdecoder/transcripts.fa.transdecoder.bed

  orfanage:
    cds: ../../data/orfanage/transcripts.cds.gtf
    # gtf_
