ref:
    t2t:
      link: https://hgdownload.soe.ucsc.edu/goldenPath/hs1/bigZips/hs1.fa.gz
      fa_gz: ../../ref/t2t/t2t.fa.gz
    afr:
      link: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/610/035/GCA_003610035.2_CAAPA_Pan-Genome/GCA_003610035.2_CAAPA_Pan-Genome_genomic.fna.gz
      fa_gz: ../../ref/afr_contigs/afr_contigs.fa.gz

    fa: /gpfs/projects/bsc83/Data/assemblies/GRCh38/GRCh38.primary_assembly.genome.fa
    gtf: /gpfs/projects/bsc83/Data/gene_annotations/gencode/v47/gencode.v47.primary_assembly.annotation.gtf

    pc_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/gencode.v46.pc_translations.fa.gz
    pc_gz: ../../ref/pc_translations.fa.gz
    pc: ../../ref/pc_translations.fa
    pc_renamed: ../../ref/pc_translations_renamed.fa

    cpat:
      model_link: https://sourceforge.net/projects/rna-cpat/files/prebuilt_models/Human_logitModel.RData/download
      model: ../../ref/cpat/cpat_model.RData
      hexamer_link: https://sourceforge.net/projects/rna-cpat/files/prebuilt_models/Human_Hexamer.tsv/download
      hexamer: ../../ref/hexamer.tsv

gtex:
    gtf_link: https://storage.googleapis.com/adult-gtex/long-read-data/v9/long-read-RNA-seq/flair_filter_transcripts.gtf.gz
    gtf_gz: ../../data/gtex/flair_filter_transcripts.gtf.gz
    gtf: ../../data/gtex/flair_filter_transcripts.gtf
    # filt_gtf: data/gtex/flair_filter_transcripts_no_novel_genes.gtf
    ab_link: https://storage.googleapis.com/adult-gtex/long-read-data/v9/long-read-RNA-seq/quantification_flair_filter.tpm.txt.gz
    ab_gz: ../../data/gtex/gtex_abundance.tsv.gz
    ab: ../../data/gtex/gtex_abundance.tsv
    ab_fmt: ../../data/gtex/gtex_abundance_formatted.tsv

    cerb:
      ics: ../../data/gtex/cerb/ics.tsv

chess:
    gtf_link: https://github.com/chess-genome/chess/releases/download/v.3.1.3/chess3.1.3.GRCh38.gtf.gz
    gtf_gz: ../../data/chess/chess.gtf.gz
    gtf: ../../data/chess/chess.gtf

    cerb:
      ics: ../../data/chess/cerb/ics.tsv

enc:
  gtf_link: https://zenodo.org/records/10869841/files/cerberus.gtf?download=1
  gtf_gz: ../../data/enc/chess.gtf.gz
  gtf: ../../data/enc/chess.gtf

  cerb:
    ics: ../../data/enc/cerb/ics.tsv


lr:
  fastq: /gpfs/projects/bsc83/Projects/pantranscriptome/pclavell/02_ONT_preprocessing/data/q10/{lab_sample}_preprocessed_Q10.fastq.gz

  gtf: /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/merged/240909_merged.gtf # whole post-merge GTF
  # gtf: /gpfs/home/bsc/bsc083001/mele_lab/projects/240706_pantranscriptome_cerberus_gtf_merge/merge_only_ics/data/flair/raw/GM10492_1.gtf # test for just one sample
  gtf_no_spike: ../../data/transcripts_no_spike.gtf
  t_fa: ../../data/transcripts.fa

  transdecoder:
    pep: ../../data/transdecoder/transcripts.fa.transdecoder.pep
    gff3: ../../data/transdecoder/transcripts.fa.transdecoder.gff3
    cds: ../../data/transdecoder/transcripts.fa.transdecoder.cds
    bed: ../../data/transdecoder/transcripts.fa.transdecoder.bed

  orfanage:
    query: ../../data/protein/transcripts_orfanage_ready_query.gtf
    ready_annot: ../../data/protein/transcripts_orfanage_ready_annotation.gtf
    cds: ../../data/protein/transcripts_orfanage_cds.gtf
    cds_to_be_predicted: ../../data/protein/transcripts_cpat_cds_to_be_predicted.gtf
    cds_filtered: ../../data/protein/transcripts_orfanage_cds_filtered.gtf
    orfs: ../../data/protein/transcripts_orfanage_orfs.fa
    stop_codon_orf: ../../data/protein/transcripts_orfanage_cds_filtered_stop_codon_corrected.gtf
    missing_cds: ../../data/protein/transcripts_missing_cds.fa

  cpat:
    r: ../../data/protein/transcripts.r
    orf_seqs: ../../data/protein/transcripts.ORF_seqs.fa
    prob_tsv: ../../data/protein/transcripts.ORF_prob.tsv
    prob_best: ../../data/protein/transcripts.ORF_prob.best.tsv
    log: ../../data/protein/transcripts_cpat.output
    err: ../../data/protein/transcripts_cpat.error
    no_orf: ../../data/protein/transcripts.no_ORF.txt
    orf_remaining: ../../data/protein/transcripts.ORF_remaining.tsv
    orf_completeness: ../../data/protein/transcripts_ORF_completeness.tsv
    cds_coords: ../../data/protein/transcripts_cpat_with_cds.gtf
    unsourced: ../../data/protein/transcripts_protein_unsourced.gtf
    protein: ../../data/protein/transcripts_protein.gtf
    orf: ../../data/protein/transcripts_ORF.fa
    protein_fa: ../../data/protein/transcripts_protein.fa

  blast:
    out: ../../data/protein/transcripts_blastp.out
    blast_db: ../../data/protein/gencode.pc_translations_renamed.pog

  sqanti_protein:
      ref_exons: ../../data/protein/transcripts_gencode.transcript_exons_only.gtf
      ref_cds_renamed: ../../data/protein/transcripts_gencode.cds_renamed_exon.gtf
      data_exons: ../../data/protein/transcripts.transcript_exons_only.gtf
      data_cds_renamed: ../../data/protein/transcripts.cds_renamed_exon.gtf
      best_orf: ../../data/protein/transcripts_best_orf.tsv
      classified: ../../data/protein/transcripts.sqanti_protein_classification.tsv

  protein:
    summary: ../../data/protein/transcripts_protein_annotation.tsv

  map:
    t2t:
      sam: ../../data/map/t2t/{sample}.sam
      sam_filt: ../../data/map/t2t/{sample}_filt.sam
      bam: ../../data/map/t2t/{sample}.bam
    afr:
      sam: ../../data/map/afr/{sample}.sam
      sam_filt: ../../data/map/afr/{sample}_filt.sam
      bam: ../../data/map/afr/{sample}.bam



  #
  #   cds: ../../data/orfanage/transcripts.cds.gtf
  #   cds_pred: ../../data/orfanage/transcripts.cds_pred.gtf
  #   cds_filt: ../../data/orfanage/transcripts.cds_filt.gtf
  #   cds_stop: ../../data/orfanage/transcripts.orfs_stop.fa
  #   cds_stop_corr: ../../data/orfanage/transcripts.orfs_stop_corr.gtf
  #   cds_for_cpat: ../../data/orfanage/transcripts.cds_for_cpat.fa
  #
  # cpat:
  #   r: ../../data/cpat/transcripts.r
  #   orf_fa: ../../data/cpat/transcripts_ORF_seqs.fa
  #   prob: ../../data/cpat/transcripts_ORF_prob.tsv
  #   prob_best: ../../data/cpat/transcripts_ORF_prob.best.tsv
  #   log: ../../data/cpat/transcripts_cpat.output
  #   err: ../../data/cpat/transcripts_cpat.error
  #   no_orf: ../../data/cpat/transcripts_no_ORF.txt
  #   filt: ../../data/cpat/transcripts_ORF_remaining.tsv
  #   orf_complete: ../../data/cpat/transcripts_ORF_completeness.tsv
  #   cds_coords: ../../data/cpat/transcripts_cpat_with_cds.gtf
  #   protein_unsourced: ../../data/cpat/transcripts_protein_unsourced.gtf


  novel_gene:
    tids: /gpfs/projects/bsc83/Projects/pantranscriptome/pclavell/04_transcriptome_assembly/04_evaluation/02_sqanti/data/240909merge/novelgene_transcripts.txt
    gtf: ../../data/novel_gene/novel_genes.gtf
    gtf_built: ../../data/novel_gene/novel_genes_built.gtf
    gtf_fmt: ../../data/novel_gene/novel_genes_fmt.gtf
    gtf_nov_known_gene: ../../data/transcripts_novel_gene_loci.gtf



params:
  orfanage:
    min_orf_len_nt: 100
  cpat:
    top_orf: 50
    cutoff_1: 0.725
    cutoff_2: 0.364
  blast:
    eval: 1.0e-10

software:
  buildLoci: /gpfs/home/bsc/bsc083001/mele_lab/bin/buildLoci/buildLoci.pl
