ref:
  alt:
    fa_gz: ../../ref/{assembly}/{assembly}.fa.gz
    fa_mmi: ../../ref/{assembly}/{assembly}.fa.mmi
    t2t:
      link: https://hgdownload.soe.ucsc.edu/goldenPath/hs1/bigZips/hs1.fa.gz
    afr:
      link: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/610/035/GCA_003610035.2_CAAPA_Pan-Genome/GCA_003610035.2_CAAPA_Pan-Genome_genomic.fna.gz
    hg38:
      link: #/gpfs/projects/bsc83/Data/assemblies/GRCh38/GRCh38.primary_assembly.genome.fa for hg38
    personal:
      fa_gz: ../../ref/{assembly_sample}/{assembly_sample}.fa.gz
      fa_mmi: ../../ref/{assembly_sample}/{assembly_sample}.fa.mmi

      pat_fa_gz: ../../ref/{assembly_sample}/{assembly_sample}_pat.fa.gz
      pat_y_fa_gz: ../../ref/{assembly_sample}/{assembly_sample}_pat_y.fa.gz # only the y chrom



  # fa: /gpfs/projects/bsc83/Data/assemblies/GRCh38/modified/GRCh38.primary_assembly.sirvset4.genome.fa
  fa: ../../ref/hg38.fa
  fa_mmi: ../../ref/hg38.fa.mmi
  gtf: /gpfs/projects/bsc83/Data/gene_annotations/gencode/v47/gencode.v47.primary_assembly.annotation.gtf

  pc_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/gencode.v46.pc_translations.fa.gz
  pc_gz: ../../ref/pc_translations.fa.gz
  pc: ../../ref/pc_translations.fa
  pc_renamed: ../../ref/pc_translations_renamed.fa

  cpat:
    model_link: https://sourceforge.net/projects/rna-cpat/files/prebuilt_models/Human_logitModel.RData/download
    model: ../../ref/cpat/cpat_model.RData
    hexamer_link: https://sourceforge.net/projects/rna-cpat/files/prebuilt_models/Human_Hexamer.tsv/download
    hexamer: ../../ref/hexamer.tsv

  v47_kallisto:
    ind: ../../ref/v47_kallisto/hg38_v47_k-63.idx
    t_fa: ../../ref/v47_kallisto/hg38_v47_transcripts.fa
    t2g: ../../ref/v47_kallisto/hg38_v47.t2g
    t2g_8col: ../../ref/v47_kallisto/hg38_v47_8col.t2g
    t2t: ../../ref/v47_kallisto/hg38_v47.t2t


  kallisto:
    ind: ../../ref/kallisto/hg38_v47_k-63.idx
    t_fa: ../../ref/kallisto/hg38_v47_transcripts.fa
    t2g: ../../ref/kallisto/hg38_v47.t2g
    t2g_8col: ../../ref/kallisto/hg38_v47_8col.t2g
    t2t: ../../ref/kallisto/hg38_v47.t2t

gtex:
    gtf_link: https://storage.googleapis.com/adult-gtex/long-read-data/v9/long-read-RNA-seq/flair_filter_transcripts.gtf.gz
    gtf_gz: ../../data/gtex/flair_filter_transcripts.gtf.gz
    gtf: ../../data/gtex/flair_filter_transcripts.gtf
    # filt_gtf: data/gtex/flair_filter_transcripts_no_novel_genes.gtf
    ab_link: https://storage.googleapis.com/adult-gtex/long-read-data/v9/long-read-RNA-seq/quantification_flair_filter.tpm.txt.gz
    ab_gz: ../../data/gtex/gtex_abundance.tsv.gz
    ab: ../../data/gtex/gtex_abundance.tsv
    ab_fmt: ../../data/gtex/gtex_abundance_formatted.tsv

    cerb:
      ics: ../../data/gtex/cerb/ics.tsv

chess:
    gtf_link: https://github.com/chess-genome/chess/releases/download/v.3.1.3/chess3.1.3.GRCh38.gtf.gz
    gtf_gz: ../../data/chess/chess.gtf.gz
    gtf: ../../data/chess/chess.gtf

    cerb:
      ics: ../../data/chess/cerb/ics.tsv

enc:
  gtf_link: https://zenodo.org/records/10869841/files/cerberus.gtf?download=1
  gtf_gz: ../../data/enc/enc.gtf.gz
  gtf: ../../data/enc/enc.gtf

  cerb:
    ics: ../../data/enc/cerb/ics.tsv


lr:
  meta: ../../data/pantranscriptome_samples_metadata.tsv
  fastq: /gpfs/projects/bsc83/Projects/pantranscriptome/pclavell/02_ONT_preprocessing/data/q7/{lab_sample}_preprocessed_Q7.fastq.gz
  fastq_reads: ../../data/{sample}_fastq_read_ids.txt
  fastq_n_reads: ../../data/{sample}_fastq_n_reads.txt
  fastq_n_reads_summary: ../../data/fastq_n_reads.txt

  gtf: /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/merged/240909_merged.gtf
  gtf_chr_renamed: /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/merged/240909_merged_withoutchrEBV.gtf # whole post-merge GTF
  # gtf: /gpfs/home/bsc/bsc083001/mele_lab/projects/240706_pantranscriptome_cerberus_gtf_merge/merge_only_ics/data/flair/raw/GM10492_1.gtf # test for just one sample
  gtf_no_spike: ../../data/transcripts_no_spike.gtf
  gtf_no_spike_no_ebv: ../../data/transcripts_no_spike_no_ebv.gtf
  gtf_filt: /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/merged/240925_filtered.gtf
  gtf_filt_with_genes: ../../data/transcripts_filt_with_gene.gtf # /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/merged/240926_filtered_with_genes.gtf
  nov_gtf_filt_with_genes: ../../data/transcripts_nov_filt_with_gene.gtf
  nov_tids: /gpfs/projects/bsc83/Projects/pantranscriptome/pclavell/04_transcriptome_assembly/04_evaluation/05_mastertable/data/240909merge_filtered_novel_transcriptid.tsv
  t_fa: ../../data/transcripts.fa

  cerb:
    ics: ../../data/cerb/ics.tsv
    nov_ics: ../../data/cerb/nov_ics.tsv

  unmerged:
    fastq: /gpfs/projects/bsc83/Projects/pantranscriptome/pclavell/02_ONT_preprocessing/data/unmerged/{sample}_preprocessed_Q7.fastq.gz

  transdecoder:
    pep: ../../data/transdecoder/transcripts.fa.transdecoder.pep
    gff3: ../../data/transdecoder/transcripts.fa.transdecoder.gff3
    cds: ../../data/transdecoder/transcripts.fa.transdecoder.cds
    bed: ../../data/transdecoder/transcripts.fa.transdecoder.bed

  orfanage:
    query: ../../data/protein/transcripts_orfanage_ready_query.gtf
    ready_annot: ../../data/protein/transcripts_orfanage_ready_annotation.gtf
    cds: ../../data/protein/transcripts_orfanage_cds.gtf
    cds_to_be_predicted: ../../data/protein/transcripts_cpat_cds_to_be_predicted.gtf
    cds_filtered: ../../data/protein/transcripts_orfanage_cds_filtered.gtf
    orfs: ../../data/protein/transcripts_orfanage_orfs.fa
    stop_codon_orf: ../../data/protein/transcripts_orfanage_cds_filtered_stop_codon_corrected.gtf
    missing_cds: ../../data/protein/transcripts_missing_cds.fa

  cpat:
    r: ../../data/protein/transcripts.r
    orf_seqs: ../../data/protein/transcripts.ORF_seqs.fa
    prob_tsv: ../../data/protein/transcripts.ORF_prob.tsv
    prob_best: ../../data/protein/transcripts.ORF_prob.best.tsv
    log: ../../data/protein/transcripts_cpat.output
    err: ../../data/protein/transcripts_cpat.error
    no_orf: ../../data/protein/transcripts.no_ORF.txt
    orf_remaining: ../../data/protein/transcripts.ORF_remaining.tsv
    orf_completeness: ../../data/protein/transcripts_ORF_completeness.tsv
    cds_coords: ../../data/protein/transcripts_cpat_with_cds.gtf
    unsourced: ../../data/protein/transcripts_protein_unsourced.gtf
    protein: ../../data/protein/transcripts_protein.gtf
    orf: ../../data/protein/transcripts_ORF.fa
    protein_fa: ../../data/protein/transcripts_protein.fa

  blast:
    out: ../../data/protein/transcripts_blastp.out
    blast_db: ../../data/protein/gencode.pc_translations_renamed.pog

  sqanti_protein:
    ref_exons: ../../data/protein/transcripts_gencode.transcript_exons_only.gtf
    ref_cds_renamed: ../../data/protein/transcripts_gencode.cds_renamed_exon.gtf
    data_exons: ../../data/protein/transcripts.transcript_exons_only.gtf
    data_cds_renamed: ../../data/protein/transcripts.cds_renamed_exon.gtf
    best_orf: ../../data/protein/transcripts_best_orf.tsv
    classified: ../../data/protein/transcripts.sqanti_protein_classification.tsv

  protein:
    summary: ../../data/protein/transcripts_protein_annotation.tsv

  map:
    sam: ../../data/map/{assembly}/{sample}.sam
    sam_filt: ../../data/map/{assembly}/{sample}_filt.sam
    bam: ../../data/map/{assembly}/{sample}.bam
    bam_sort: ../../data/map/{assembly}/{sample}_sorted.bam
    bam_ind: ../../data/map/{assembly}/{sample}_sorted.bam.bai
    bam_n_reads: ../../data/map/{assembly}/{sample}_n_reads.txt
    bam_n_reads_summary: ../../data/map/{assembly}/n_reads_summary.tsv
    bam_mapqs: ../../data/map/{assembly}/{sample}_mapqs.txt
    bam_mapqs_summary: ../../data/map/{assembly}/mapqs_summary.txt
    bam_query_covs: ../../data/map/{assembly}/{sample}_query_cov.tsv
    bam_query_covs_summary: ../../data/map/{assembly}/query_cov_summary.tsv

  map_personal:
    sam: ../../data/map_personal/{assembly_status}/{assembly_sample}_{sample}.sam
    sam_filt: ../../data/map_personal/{assembly_status}/{assembly_sample}_{sample}_filt.sam
    bam: ../../data/map_personal/{assembly_status}/{assembly_sample}_{sample}.bam
    bam_sort: ../../data/map_personal/{assembly_status}/{assembly_sample}_{sample}_sorted.bam
    bam_ind: ../../data/map_personal/{assembly_status}/{assembly_sample}_{sample}_sorted.bam.bai
    bam_n_reads: ../../data/map_personal/{assembly_status}/{assembly_sample}_{sample}_n_reads.txt
    bam_n_reads_summary: ../../data/map_personal/{assembly_status}/n_reads_summary.tsv
    bam_mapqs: ../../data/map_personal/{assembly_status}/{assembly_sample}_{sample}_mapqs.txt
    bam_mapqs_summary: ../../data/map_personal/{assembly_status}/mapqs_summary.txt
    bam_query_covs: ../../data/map_personal/{assembly_status}/{assembly_sample}_{sample}_query_cov.tsv
    bam_query_covs_summary: ../../data/map_personal/{assembly_status}/query_cov_summary.tsv

  v47_kallisto:
    odir: ../../data/v47_kallisto/{sample}/
    bus: ../../data/v47_kallisto/{sample}/output.bus
    transcripts: ../../data/v47_kallisto/{sample}/transcripts.txt
    matrix: ../../data/v47_kallisto/{sample}/matrix.ec
    flens: ../../data/v47_kallisto/{sample}/flens.txt
    bus_sort: ../../data/v47_kallisto/{sample}/output_sorted.bus

    count_pref_uniq: ../../data/v47_kallisto/{sample}/count_uniq/count
    count_mtx_uniq: ../../data/v47_kallisto/{sample}/count_uniq/count.mtx
    count_transcripts_uniq: ../../data/v47_kallisto/{sample}/count_uniq/count.genes.txt
    matrix_tsv_uniq: ../../data/v47_kallisto/{sample}/count_uniq/matrix_uniq.abundance.tsv


    count_pref: ../../data/v47_kallisto/{sample}/count
    count_mtx: ../../data/v47_kallisto/{sample}/count.mtx
    count_ec: ../../data/v47_kallisto/{sample}/count.ec.txt
    matrix_tsv: ../../data/v47_kallisto/{sample}/matrix.abundance.tsv

    quant:
      odir: ../../data/v47_kallisto_quant/{sample}
      matrix: ../../data/v47_kallisto_quant/{sample}/matrix.abundance.mtx
      matrix_tpm: ../../data/v47_kallisto_quant/{sample}/matrix.abundance.tpm.mtx
      matrix_tsv: ../../data/v47_kallisto_quant/{sample}/matrix.abundance.tsv
      matrix_tpm_tsv: ../../data/v47_kallisto_quant/{sample}/matrix.abundance.tpm.tsv
      merge_matrix_tsv: ../../data/v47_kallisto_quant/matrix.abundance.tsv
      merge_matrix_tpm_tsv: ../../data/v47_kallisto_quant/matrix.abundance.tpm.tsv


  kallisto:
    odir: ../../data/kallisto/{sample}/
    bus: ../../data/kallisto/{sample}/output.bus
    transcripts: ../../data/kallisto/{sample}/transcripts.txt
    matrix: ../../data/kallisto/{sample}/matrix.ec
    flens: ../../data/kallisto/{sample}/flens.txt
    bus_sort: ../../data/kallisto/{sample}/output_sorted.bus

    count_pref_uniq: ../../data/kallisto/{sample}/count_uniq/count
    count_mtx_uniq: ../../data/kallisto/{sample}/count_uniq/count.mtx
    count_transcripts_uniq: ../../data/kallisto/{sample}/count_uniq/count.genes.txt
    matrix_tsv_uniq: ../../data/kallisto/{sample}/count_uniq/matrix_uniq.abundance.tsv


    count_pref: ../../data/kallisto/{sample}/count
    count_mtx: ../../data/kallisto/{sample}/count.mtx
    count_ec: ../../data/kallisto/{sample}/count.ec.txt
    matrix_tsv: ../../data/kallisto/{sample}/matrix.abundance.tsv

    quant:
      odir: ../../data/kallisto_quant/{sample}
      matrix: ../../data/kallisto_quant/{sample}/matrix.abundance.mtx
      matrix_tpm: ../../data/kallisto_quant/{sample}/matrix.abundance.tpm.mtx
      matrix_tsv: ../../data/kallisto_quant/{sample}/matrix.abundance.tsv
      matrix_tpm_tsv: ../../data/kallisto_quant/{sample}/matrix.abundance.tpm.tsv
      merge_matrix_tsv: ../../data/kallisto_quant/matrix.abundance.tsv
      merge_matrix_tpm_tsv: ../../data/kallisto_quant/matrix.abundance.tpm.tsv

  unmerged_kallisto:
    odir: ../../data/unmerged_kallisto/{sample}/
    bus: ../../data/unmerged_kallisto/{sample}/output.bus
    transcripts: ../../data/unmerged_kallisto/{sample}/transcripts.txt
    matrix: ../../data/unmerged_kallisto/{sample}/matrix.ec
    flens: ../../data/unmerged_kallisto/{sample}/flens.txt
    bus_sort: ../../data/unmerged_kallisto/{sample}/output_sorted.bus

    count_pref_uniq: ../../data/unmerged_kallisto/{sample}/count_uniq/count
    count_mtx_uniq: ../../data/unmerged_kallisto/{sample}/count_uniq/count.mtx
    count_transcripts_uniq: ../../data/unmerged_kallisto/{sample}/count_uniq/count.genes.txt
    matrix_tsv_uniq: ../../data/unmerged_kallisto/{sample}/count_uniq/matrix_uniq.abundance.tsv


    count_pref: ../../data/unmerged_kallisto/{sample}/count
    count_mtx: ../../data/unmerged_kallisto/{sample}/count.mtx
    count_ec: ../../data/unmerged_kallisto/{sample}/count.ec.txt
    matrix_tsv: ../../data/unmerged_kallisto/{sample}/matrix.abundance.tsv

    quant:
      odir: ../../data/unmerged_kallisto_quant/{sample}
      matrix: ../../data/unmerged_kallisto_quant/{sample}/matrix.abundance.mtx
      matrix_tpm: ../../data/unmerged_kallisto_quant/{sample}/matrix.abundance.tpm.mtx
      matrix_tsv: ../../data/unmerged_kallisto_quant/{sample}/matrix.abundance.tsv
      matrix_tpm_tsv: ../../data/unmerged_kallisto_quant/{sample}/matrix.abundance.tpm.tsv
      merge_matrix_tsv: ../../data/unmerged_kallisto_quant/matrix.abundance.tsv
      merge_matrix_tpm_tsv: ../../data/unmerged_kallisto_quant/matrix.abundance.tpm.tsv

  v47_unmerged_kallisto:
    odir: ../../data/v47_unmerged_kallisto/{sample}/
    bus: ../../data/v47_unmerged_kallisto/{sample}/output.bus
    transcripts: ../../data/v47_unmerged_kallisto/{sample}/transcripts.txt
    matrix: ../../data/v47_unmerged_kallisto/{sample}/matrix.ec
    flens: ../../data/v47_unmerged_kallisto/{sample}/flens.txt
    bus_sort: ../../data/v47_unmerged_kallisto/{sample}/output_sorted.bus

    count_pref_uniq: ../../data/v47_unmerged_kallisto/{sample}/count_uniq/count
    count_mtx_uniq: ../../data/v47_unmerged_kallisto/{sample}/count_uniq/count.mtx
    count_transcripts_uniq: ../../data/v47_unmerged_kallisto/{sample}/count_uniq/count.genes.txt
    matrix_tsv_uniq: ../../data/v47_unmerged_kallisto/{sample}/count_uniq/matrix_uniq.abundance.tsv


    count_pref: ../../data/v47_unmerged_kallisto/{sample}/count
    count_mtx: ../../data/v47_unmerged_kallisto/{sample}/count.mtx
    count_ec: ../../data/v47_unmerged_kallisto/{sample}/count.ec.txt
    matrix_tsv: ../../data/v47_unmerged_kallisto/{sample}/matrix.abundance.tsv

    quant:
      odir: ../../data/v47_unmerged_kallisto_quant/{sample}
      matrix: ../../data/v47_unmerged_kallisto_quant/{sample}/matrix.abundance.mtx
      matrix_tpm: ../../data/v47_unmerged_kallisto_quant/{sample}/matrix.abundance.tpm.mtx
      matrix_tsv: ../../data/v47_unmerged_kallisto_quant/{sample}/matrix.abundance.tsv
      matrix_tpm_tsv: ../../data/v47_unmerged_kallisto_quant/{sample}/matrix.abundance.tpm.tsv
      merge_matrix_tsv: ../../data/v47_unmerged_kallisto_quant/matrix.abundance.tsv
      merge_matrix_tpm_tsv: ../../data/v47_unmerged_kallisto_quant/matrix.abundance.tpm.tsv



  #
  #   cds: ../../data/orfanage/transcripts.cds.gtf
  #   cds_pred: ../../data/orfanage/transcripts.cds_pred.gtf
  #   cds_filt: ../../data/orfanage/transcripts.cds_filt.gtf
  #   cds_stop: ../../data/orfanage/transcripts.orfs_stop.fa
  #   cds_stop_corr: ../../data/orfanage/transcripts.orfs_stop_corr.gtf
  #   cds_for_cpat: ../../data/orfanage/transcripts.cds_for_cpat.fa
  #
  # cpat:
  #   r: ../../data/cpat/transcripts.r
  #   orf_fa: ../../data/cpat/transcripts_ORF_seqs.fa
  #   prob: ../../data/cpat/transcripts_ORF_prob.tsv
  #   prob_best: ../../data/cpat/transcripts_ORF_prob.best.tsv
  #   log: ../../data/cpat/transcripts_cpat.output
  #   err: ../../data/cpat/transcripts_cpat.error
  #   no_orf: ../../data/cpat/transcripts_no_ORF.txt
  #   filt: ../../data/cpat/transcripts_ORF_remaining.tsv
  #   orf_complete: ../../data/cpat/transcripts_ORF_completeness.tsv
  #   cds_coords: ../../data/cpat/transcripts_cpat_with_cds.gtf
  #   protein_unsourced: ../../data/cpat/transcripts_protein_unsourced.gtf


  novel_gene:
    tids: /gpfs/projects/bsc83/Projects/pantranscriptome/pclavell/04_transcriptome_assembly/04_evaluation/02_sqanti/data/240909merge_withoutchrEBV_mastertable/240909merge_novelgene_transcripts.tsv
    gtf: ../../data/novel_gene/novel_genes.gtf
    gtf_built: ../../data/novel_gene/novel_genes_built.gtf
    gtf_fmt: ../../data/novel_gene/novel_genes_fmt.gtf
    gtf_nov_known_gene: ../../data/transcripts_novel_gene_loci.gtf
    gtf_added_gene_entries: ../../data/novel_gene/transcripts_novel_gene_loci_filt_gene_name.gtf
    # gtf_added_gene_entries: /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/merged/240917_merge_geneEntry_correctedScaffolds_nochrEBV.gtf


params:
  orfanage:
    min_orf_len_nt: 100
  cpat:
    top_orf: 50
    cutoff_1: 0.725
    cutoff_2: 0.364
  blast:
    eval: 1.0e-10

software:
  buildLoci: /gpfs/home/bsc/bsc083001/mele_lab/bin/buildLoci/buildLoci.pl
