gtex:
    gtf_link: https://storage.googleapis.com/adult-gtex/long-read-data/v9/long-read-RNA-seq/flair_filter_transcripts.gtf.gz
    gtf_gz: ../../data/gtex/flair_filter_transcripts.gtf.gz
    gtf: ../../data/gtex/flair_filter_transcripts.gtf
    # filt_gtf: data/gtex/flair_filter_transcripts_no_novel_genes.gtf
    ab_link: https://storage.googleapis.com/adult-gtex/long-read-data/v9/long-read-RNA-seq/quantification_flair_filter.tpm.txt.gz
    ab_gz: ../../data/gtex/gtex_abundance.tsv.gz
    ab: ../../data/gtex/gtex_abundance.tsv
    ab_fmt: ../../data/gtex/gtex_abundance_formatted.tsv

    cerb:
      ics: ../../data/gtex/cerb/ics.tsv

chess:
    gtf_link: https://github.com/chess-genome/chess/releases/download/v.3.1.3/chess3.1.3.GRCh38.gff.gz
    gtf_gz: ../../data/chess/chess.gtf.gz
    gtf: ../../data/chess/chess.gtf

    cerb:
      ics: ../../data/gtex/cerb/ics.tsv
