import pandas as pd
import os
import sys

p = os.path.dirname(os.path.dirname(os.getcwd()))+'/scripts/'
sys.path.append(p)
#
# from sm_utils import *
# from utils import *
# from vcf_utils import *

c_dir = '../common/'

meta_file = 'config.tsv'
configfile: '../config.yml'

include: f'{c_dir}download.smk'
include: f'{c_dir}samtools.smk'
include: f'{c_dir}winnowmap.smk'
include: f'{c_dir}bigwig.smk'
include: f'{c_dir}variant_calling.smk'
include: f'{c_dir}formatting.smk'
include: f'{c_dir}phasing.smk'
include: f'{c_dir}cerberus.smk'
include: f'{c_dir}bedtools.smk'
include: f'{c_dir}transdecoder.smk'


rule all:
    input:
        config['lr']['transdecoder']['pep']

use rule bed_to_fasta as gtf_to_t_fa with:
    input:
        bed = config['lr']['gtf'],
        fa = config['ref']['g_fa']
    output:
        fa = config['lr']['t_fa']

use rule find_orfs as td_find_orfs with:
    input:
        fa = config['lr']['t_fa']
    params:
        odir = get_odir_from_fname(config['lr']['transdecoder']['pep'])
    output:
        pep = config['lr']['transdecoder']['pep'],
        gff3 = config['lr']['transdecoder']['gff3'],
        cds = config['lr']['transdecoder']['cds'],
        bed = config['lr']['transdecoder']['bed']
